arsiv/arsiv/Models/EntityFramework/Kitaplar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arsiv.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.İslem = new HashSet<İslem>();
        }
    
        public int ID { get; set; }
        public string Kitapadı { get; set; }
        public Nullable<int> Tur_id { get; set; }
        public Nullable<System.DateTime> basimyili { get; set; }
        public Nullable<int> sayfasayisi { get; set; }
        public Nullable<int> Yazar_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<İslem> İslem { get; set; }
        public virtual Turler Turler { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
    }
}

arsiv/arsiv/Controllers/KitaplarController.cs
using arsiv.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using arsiv.ViewModels;

namespace arsiv.Controllers
{
    [Authorize]
    public class KitaplarController : Controller
    {
        ArsivEntities db = new ArsivEntities();
        // GET: Kitaplar
        public ActionResult Index()
        {
            var model = db.Kitaplar.Include(x => x.Turler).Include(x => x.Yazarlar).ToList();
            return View(model);
        }
        public ActionResult Yeni()
        {
            var model = new KitaplarFormViewModel()
            {
                Turlers=db.Turler.ToList(),
                Yazarlars=db.Yazarlar.ToList()
            };
            return View("KitaplarForm", model);
        }
        [HttpGet]
        public ActionResult Kaydet()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Kaydet(Kitaplar kitaplar)
        {
            if (kitaplar.ID == 0 )
            {
                db.Kitaplar.Add(kitaplar);
            }
            else//Güncelleme
            {
                db.Entry(kitaplar).State = System.Data.Entity.EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Guncelle(int id)
        {
            var model = new KitaplarFormViewModel() {
                Turlers = db.Turler.ToList(),
                Yazarlars = db.Yazarlar.ToList(),
                Kitaplar = db.Kitaplar.Find(id)
            };
            return View("KitaplarForm", model);
        }
        public ActionResult Sil(int id)
        {
            var silinecekKitaplar = db.Kitaplar.Find(id);
            if (silinecekKitaplar == null)
                return HttpNotFound();
            db.Kitaplar.Remove(silinecekKitaplar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

arsiv/arsiv/Views/Kitaplar/Index.cshtml

@model List<arsiv.Models.EntityFramework.Kitaplar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/shared/_Layout.cshtml";
}
@Html.ActionLink("Yeni Kitap Kaydı","Yeni",null,new {@class="btn btn-success" })
<h2>Kitap Listesi</h2>

<table class="table table-bordered" id="tblKitaplar">
    <thead>
        <tr>
            <th>Kitap No</th>
            <th>Kitapadı</th>
            <th>Türü</th>
            <th>basimyili</th>
            <th>sayfasayisi</th>
            <th>Yazar Adı</th>
            <th>Güncelle</th>
            <th>Sil</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var kitaplar in Model)
        {
            <tr>
                <td>@kitaplar.ID</td>
                <td>@kitaplar.Kitapadı</td>
                <td>@kitaplar.Turler.Turismi</td>
                <td>@kitaplar.basimyili</td>
                <td>@kitaplar.sayfasayisi</td>
                <td>@kitaplar.Yazarlar.AdSoyad</td>
                <td>@Html.ActionLink("Güncelle","Guncelle",new{id = kitaplar.ID},new {@class = "btn btn-success"})</td>
                <td>@Html.ActionLink("Sil", "Sil", new { id = kitaplar.ID }, new { @class = "btn btn-danger" })</td>
            </tr>
        }
    </tbody>
</table>

arsiv/arsiv/Views/Kitaplar/KitaplarForm.cshtml
@model arsiv.ViewModels.KitaplarFormViewModel
@{
    ViewBag.Title = "KitaplarForm";
    Layout = "~/Views/shared/_Layout.cshtml";
}

<h2>Yeni Kitap</h2>
@using (Html.BeginForm("Kaydet", "Kitaplar", FormMethod.Post))
{

    <div class="form-group">
        @Html.LabelFor(m => m.Kitaplar.Kitapadı)
        @Html.TextBoxFor(m => m.Kitaplar.Kitapadı, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Kitaplar.Tur_id)
        @Html.DropDownListFor(m => m.Kitaplar.Tur_id, new SelectList(Model.Turlers, "ID", "Turismi"),new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Kitaplar.basimyili)
        @Html.TextBoxFor(m => m.Kitaplar.basimyili, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Kitaplar.sayfasayisi)
        @Html.TextBoxFor(m => m.Kitaplar.sayfasayisi, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Kitaplar.Yazar_id)
        @Html.DropDownListFor(m => m.Kitaplar.Yazar_id, new SelectList(Model.Yazarlars, "ID", "AdSoyad"),new { @class = "form-control" })
    </div>
    @Html.HiddenFor(m=>m.Kitaplar.ID)
    <button type="submit" clsass="btn btn-secondary">Kaydet</button>
}
