arsiv/arsiv/Controllers/SecurityController.cs
using arsiv.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace arsiv.Controllers
{
    
    public class SecurityController : Controller
    {
        ArsivEntities db = new ArsivEntities();
        // GET: Security
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(Kullanici kullanici)
        {
            var kullaniciInDb = db.Kullanici.FirstOrDefault(x => x.Ad == kullanici.Ad && x.Sifre == kullanici.Sifre);
            if (kullaniciInDb == null)
            {
                ViewBag.Mesaj = "Kullancı Adı veya Şifre Hatalı";
                return View();
            }
            else
            {
                FormsAuthentication.SetAuthCookie(kullaniciInDb.Ad,false);
                return RedirectToAction("Index", "İslem");
            }
            
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return View("Login");
        }
    }
}

arsiv/arsiv/Views/Security/Login.cshtml
@model arsiv.Models.EntityFramework.Kullanici
    @{
        Layout = null;
    }

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <!--Pulling Awesome Font -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/login.css" rel="stylesheet" />

    <div class="container">
        <h3>Lütfen Giriş Yapınız...</h3>
        @ViewBag.Mesaj
        <div class="row">
            <div class="col-md-offset-5 col-md-3">
                @using (Html.BeginForm("Login", "Security", FormMethod.Post))
                {
                    <div class="form-login">
                        <h4>Hoşgeldiniz</h4>
                        @Html.LabelFor(m => m.Ad)
                        @Html.TextBoxFor(m => m.Ad, new { @class = "form-control", placeholder = "Kullancı Adı" })
                    </div>
                    <div class="form-login">
                        @Html.LabelFor(m => m.Sifre)
                        @Html.PasswordFor(m => m.Sifre, new { @class = "form-control", placeholder = "Şifre" })
                    </div>
                    <button type="submit" class="btn btn-block btn-success">Giriş Yap</button>
                }

            </div>

        </div>
    </div>